info:
  contact: {}
paths:
  /health:
    get:
      description: This endpoint returns the health status of the server.
      responses:
        "200":
          description: Server is running
          schema:
            type: string
      summary: Server Health Check
  /webhook:
    post:
      consumes:
      - application/json
      description: This endpoint receives a webhook and performs an action.
      parameters:
      - description: Webhook Payload
        in: body
        name: webhook
        required: true
        schema:
          type: string
      produces:
      - application/json
      responses:
        "200":
          description: Webhook received
          schema:
            type: string
        "400":
          description: Webhook error
          schema:
            type: string
      summary: Webhook Receiver
swagger: "2.0"
